services:
  - type: web
    name: mhz-erp-cloud
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
